apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-agent
spec:
  selector:
    matchLabels:
      app: mcp-agent-npu
  template:
    metadata:
      labels:
        app: mcp-agent-npu
    spec:
      nodeSelector:
        accelerator: npu
