apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp
nameSuffix: -npu
resources:
  - ../../base
patchesStrategicMerge:
  - configmap-patch.yaml
  - deployment-patch.yaml
  - service-patch.yaml
